name: Punch in

on:
  schedule:
    - cron: '0 2 * * 1-5'
    - cron: '0 11 * * 1-5'

jobs:
  attendence:
    name: do_punch
    runs-on: ubuntu-latest
    env:
      ACCOUNT: ${{ secrets.ACCOUNT}}
      PASSWORD: ${{ secrets.PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: debug
      #   uses: ./
      #   with:
      #     mode: out
      - name: Punch in
        if: github.event.schedule == '0 2 * * 1-5'
        uses: ./
        with:
          mode: in
      - name: Punch out
        if: github.event.schedule == '0 11 * * 1-5'
        uses: ./
        with:
          mode: out
